### ISSUE TITLE
Review, general issues

### ISSUE THREAD

**Issue by vr8hub** [jlund/jack-black_you-cant-win#1]
- [x] The CSS for acknowledgements is not needed; the rule in 7.2.10.9 is only for those that don't have a title, and the Acknowledgements have a title.
- [x] We don't put in a dc:source for the cover art, only for the scans and transcriptions.
- [x] Robert Herrick and Van Gogh should have a full-name attribute in the metadata. (I just noticed that is only mentioned in the author section of the manual, but we put it in, as well as Wiki and NACOAF, on all contributors that have the info available.)
- [x] Did you look into other subjects (dc:subject, not se:subject) for the book? Autobiography is the most obvious, but maybe one or more prison-related ones, or are there any for safe-cracking, or criminal gangs, etc.?
- [x] I know this is picky, but we don't mix editorial and non-editorial changes in the same commit, even when they're trivial. So, e.g., in e75eb0c, you change the A.M. to a.m., which is editorial, and tag it as an abbreviation, which is not. Those should be two different commits.
- [x] Re 279efe25 (the "ducat" letter), note that the "Sometimes" is not indented in the scans. It is thus a continuation of the paragraph, not a new one, and therefore 1) should have a continued class on the paragraph, and 2) does not need the opening quote. IOW, the semantic paragraph begins with `Well, it's this way…` and ends with `…You ain't exactly beggin'.` and has a blockquote in the middle. See [8.4.2.1](https://standardebooks.org/manual/1.7.0/single-page#8.4.2.1).

**Comment by jlund** [comment]
1 through 3 are done. Thanks for the clarification!

> So, e.g., in https://github.com/jlund/jack-black_you-cant-win/commit/e75eb0c9a4a19fb44e1e01888bc34c1100f80762, you change the A.M. to a.m., which is editorial, and tag it as an abbreviation, which is not. Those should be two different commits.

Good catch. I split this into two commits in an interactive rebase.

> Re https://github.com/jlund/jack-black_you-cant-win/commit/279efe25dfb86b76f83e46a9492f2bc936dc5a98 (the "ducat" letter), note that the "Sometimes" is not indented in the scans. It is thus a continuation of the paragraph...

I caught this during my second proofreading pass about a month ago and I fixed it just as you suggested in [`9114ec2`](https://github.com/jlund/jack-black_you-cant-win/commit/9114ec2fd1bd5173fbe642df33d308b81d02ba97). Sorry about the confusion! I will drop the initial editorial commit (that was later reverted and fixed) while I'm rewriting history.

> Did you look into other subjects (dc:subject, not se:subject) for the book?

The Library of Congress [catalog listing](https://lccn.loc.gov/26017437) for the 1926 edition had "Thieves" as the only subject, which is why I went with that. I agree with you that it feels incomplete!

I found [another listing](https://lccn.loc.gov/92017682) that includes "Criminals--United States--Biography" and "Criminals--Canada--Biography."

**Is it OK to deviate from the LC Subject list in the LoC catalog listing?** If so, here's a proposed list. Let me know what you think:
* [Autobiography](https://id.loc.gov/authorities/subjects/sh85010050)
* [Burglars](http://id.loc.gov/authorities/subjects/sh93008824)
* [Criminals](http://id.loc.gov/authorities/subjects/sh85036577)
* [Escapes](https://id.loc.gov/authorities/subjects/sh85044783)
* [Ex-convicts](http://id.loc.gov/authorities/subjects/sh85046058)
* [Homeless persons](http://id.loc.gov/authorities/subjects/sh85061718)
* [Jewel thieves](http://id.loc.gov/authorities/subjects/sh85070191)
* [Prison discipline](https://id.loc.gov/authorities/subjects/sh85106926)
* [Prison reform](https://id.loc.gov/authorities/subjects/sh2020008924)
* [Prison violence](https://id.loc.gov/authorities/subjects/sh85106948)
* [Rogues and vagabonds](http://id.loc.gov/authorities/subjects/sh85114840)
* [Safes](https://id.loc.gov/authorities/subjects/sh85116439)

**Comment by vr8hub** [comment]
Re 279efe2, that's totally my bad, I should have noticed that later commit (or checked the actual build!). If you fixed it later, it's fine, don't worry about deleting the commit. (This is doubly bad because I actually had a note on a different commit, and saw that was corrected later so got rid of my note; that should have alerted me that it might have happened with other commits!)

Interesting about the LoC listing. Normally our subjects come from  whatever PG has on them, and we never have figured out how they go about assigning them. So, yes, I think it's fine to assign our own. Since this is an _auto_biography I'm ambivalent about the Criminals--?--Biography ones. Of the others you list, I'm not sure about "Homeless persons" and "Prison discipline" and "Safes"; I didn't get the sense that the book was "about" those things (if there was a "Safe cracking" it might be different).
But, the decision is yours—you've read the book and I haven't. :)

**Comment by jlund** [comment]
Excellent. Thanks for the suggestions. I agree with your reservations on those. I just committed a new list. I substituted "Burglars" for "Thieves," which is the broader term and also matches the LC Subject in the canonical LoC listing.
