### ISSUE TITLE
Review, spelling changes

### ISSUE THREAD

**Issue by vr8hub** [jlund/jack-black_you-cant-win#2]
Re all the spelling changes, we don't generally mess with words that modernize spelling doesn't, unless it's an exception cleared with Alex. They're not necessarily _bad_*, they're just not necessary, and cause a lot of work both for producer and the reviewer, because the latter has to look at each one, look it up in M-W to confirm it is valid, etc.

In addition, we rarely change things that are found in M-W, even as a variant, and we don't change to things that _aren't_ in M-W. We also don't generally remove dashes, since modernize spelling _does_ handle all those (blah-blah to blahblah). It doesn't handle spaces (blah blah to blah-blah) or changing dashes to spaces (blah-blah to blah blah), but, again, see above.

- [x] 5ac0219; ax is valid (see [here](https://www.merriam-webster.com/words-at-play/ax-vs-axe-difference)). Additionally, we have "ax" all over the corpus.
- [x] e129db7; Lodgment is actually the preferred spelling, so should be left.
- [x] f73f8ef; dominos is a valid spelling of the plural of domino.
- [x] 53366cc; plain-clothes is also found all over the corpus.
- [x] 97130c1; [leary](https://www.merriam-webster.com/dictionary/leary) is a valid spelling.
- [x] b915f72; neither winter-money nor winter money is in M-W. This makes it purely an editorial decision, and the actual book editor wins. :)
- [x] 8b6da99; Alex has been asked about "worth while" multiple times (at least two of them by me) and has said each time that it should stay as is. If we ever do update it, we'll have to do it across the entire corpus.
- [x] 14f113b; [stanch](https://www.merriam-webster.com/dictionary/stanch) is valid.

For all of these, the cleanest thing is to just drop the commit in an interactive rebase. If you're not comfortable doing a rebase, then you can just revert them/reverse them.

**Comment by jlund** [comment]
These were all dropped in an interactive rebase as you suggested. I am glad that I committed them individually so that they would be easy to ditch later :)

I totally understand and appreciate the clarification here, and I agree with these changes, but should we add a bit more context in this section of the [step-by-step guide](https://standardebooks.org/contribute/producing-an-ebook-step-by-step)?

> **Archaic spellings.** Is a particular word spelled in a surprising way? Mark it to check if it should be modernized. The [Google Books Ngram Viewer](https://books.google.com/ngrams/) is a great tool to get an idea of whether a word used to be spelled one way, but isn’t spelled that way anymore. Remember to change spellings in their own commits, prefaced with [Editorial]!

I came away from that thinking that I should check the Ngram graphs and commit accordingly if any spelling choices felt odd or outdated to me during the proofreading process.

The Google Ngram graphs for [dominos vs. dominoes](https://books.google.com/ngrams/graph?content=dominos%2Cdominoes&year_start=1800&year_end=2019&corpus=26&smoothing=3&direct_url=t1%3B%2Cdominos%3B%2Cc0%3B.t1%3B%2Cdominoes%3B%2Cc0), [plain-clothes vs. plainclothes](https://books.google.com/ngrams/graph?content=plain-clothes%2Cplainclothes&year_start=1800&year_end=2019&corpus=26&smoothing=3&direct_url=t1%3B%2Cplain%20-%20clothes%3B%2Cc0%3B.t1%3B%2Cplainclothes%3B%2Cc0), [ax vs. axe](https://books.google.com/ngrams/graph?content=ax%2Caxe&year_start=1800&year_end=2019&corpus=26&smoothing=3&direct_url=t1%3B%2Cax%3B%2Cc0%3B.t1%3B%2Caxe%3B%2Cc0) (the article you linked to refers to "axe" as "The Current Champion" too), [leary vs. leery](https://books.google.com/ngrams/graph?content=leary%2Cleery&year_start=1800&year_end=2019&corpus=26&smoothing=3&direct_url=t1%3B%2Cleary%3B%2Cc0%3B.t1%3B%2Cleery%3B%2Cc0), and [stanch vs. staunch](https://books.google.com/ngrams/graph?content=stanch%2Cstaunch&year_start=1800&year_end=2019&corpus=26&smoothing=3&direct_url=t1%3B%2Cstanch%3B%2Cc0%3B.t1%3B%2Cstaunch%3B%2Cc0#t1%3B%2Cstanch%3B%2Cc0%3B.t1%3B%2Cstaunch%3B%2Cc0) all seemed to indicate pretty clear preferences in favor of these editorial commits, so I was just trying to follow that guidance from the step-by-step guide.

"Lodgment" and "winter-money" (and "worth while") were definitely just straight-up mistakes though :upside_down_face:  Thanks for catching them!

Do the rest of the Ngram-influenced editorial "less-popular-variant -> modern-variant" commits look OK?

**Comment by vr8hub** [comment]
Well, first, this is an inexact science; you would get different reviews from each of our reviewers, and all of them would be different than Alex's. :)

From my view, in these cases, none of the words mentioned qualify as "archaic" spelling (as opposed to, e.g., "tost" instead of tossed, or "tryal" instead of trial); first, this book was written in the 1920's, so nothing would qualify as "archaic" :), and second, they are listed as alternate spellings in a modern dictionary.

This is also why I use the corpus as reference; if we have the word spelled that way elsewhere in the corpus, then it's a good indication we're OK with it. And if we're not, all of them will have to be corrected at once. (Github's new code search at cs.github.com is great for this; I think you still have to sign up for it, but they're accepting pretty much everyone.)

My (personal) general rule is that if it's listed as a variant in M-W, I rarely mess with it. (I made an exception there for "connecter" in my first email, but that was because it doesn't occur elsewhere in the corpus.) And I almost never mess with dashed words that modernize spelling doesn't correct; there are just too many, and it's a rabbit-hole of unending length, and correcting them in one place doesn't really do anything for us.

Alex just talked about this subject on the list in reply to a question about "Christmas-day," see [here](https://groups.google.com/g/standardebooks/c/a4UMiLxeWXI).

And, at the end of the day, if you feel strongly about any of them, you are _always_ welcome to ask Alex about them. I am definitely not the final word here. :)

**Comment by vr8hub** [comment]
Oops, sorry, didn't answer your question—yes, if I didn't comment on them, then I think they're fine.

**Comment by jlund** [comment]
Thanks for the detailed reply, and for sharing Alex's recent reply too. That all makes sense, and I totally see what you mean with those truly archaic examples. Apples and oranges.

Your suggestion to use the new code search functionality to check within other SE repos is great too. I have occasionally been doing a very frustrating and very slow version of that in some cases by using `org:standardebooks <search term>` in the standard GitHub search box.

> ...correcting them in one place doesn't really do anything for us.

This really resonates with me. If I ever feel strongly about anything that `se modernize-spelling` doesn't modernize in the future, I'll bring it up on the mailing list and submit a pull request instead of doing these one-off commits.
